# Use the official Node.js image as the base image
FROM node:17

# Create and set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose port 3000 (ตรงกับ Express.js)
EXPOSE 3000

# Set the NODE_ENV environment variable to 'development'
ENV NODE_ENV=development

# Use nodemon to start the Express application
CMD ["npx", "nodemon", "app.js"]
